spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: root
  datasource:
    url: jdbc:mariadb://database:3306/application
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
